service: default
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: ssl
  version: latest

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- node_modules

handlers:
- url: /api/.*
  script: api.app
  secure: always

- url: /search
  script: api.app
  secure: always

- url: /
  static_dir: client
  login: admin
  secure: always
